# Computes per-target correlation numbers and emits LaTeX table bodies for the SI.
import os, sys
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import RESULTS_DIR, PAPER_DIR
import numpy as np, pandas as pd
from scipy.stats import spearmanr, rankdata

def partial_spearman(x, y, Z):
    m = np.isfinite(x) & np.isfinite(y) & np.all(np.isfinite(Z), axis=1)
    x, y, Z = x[m], y[m], Z[m]
    if len(x) < 15: return np.nan
    xr, yr = rankdata(x), rankdata(y)
    Zr = np.column_stack([np.ones(len(xr))] + [rankdata(Z[:, j]) for j in range(Z.shape[1])])
    rx = xr - Zr @ np.linalg.lstsq(Zr, xr, rcond=None)[0]
    ry = yr - Zr @ np.linalg.lstsq(Zr, yr, rcond=None)[0]
    return float(np.corrcoef(rx, ry)[0, 1]) if rx.std() > 1e-9 and ry.std() > 1e-9 else np.nan

df = pd.read_csv(os.path.join(RESULTS_DIR, "all_per_compound.csv"))
glob = pd.read_csv(os.path.join(RESULTS_DIR, "tableE_global_indices.csv")).set_index("dataset")
gnn  = pd.read_csv(os.path.join(RESULTS_DIR, "gnn_fixed_vs_tuned.csv")).set_index("dataset")

rows = []
for ds, g in df.groupby("dataset"):
    def rho(col):
        s = g[[col, "rf_err"]].dropna()
        return spearmanr(s[col], s.rf_err).statistic if len(s) > 10 else np.nan
    Z = g[["nn_sim", "local_dens"]].values
    rows.append(dict(
        target=ds, n=int(len(g)), cliff_frac=float(g.cliff_mol.mean()),
        rho_dirichlet=rho("dirichlet"), rho_lipschitz=rho("lipschitz"),
        rho_nbr_disp=rho("nbr_disp"), rho_sali_mean=rho("sali_mean"),
        partial_nbr_disp_AD=partial_spearman(g.nbr_disp.values, g.rf_err.values, Z),
        rogi=float(glob.loc[ds, "rogi"]),
        mae_rf=float(gnn.loc[ds, "mae_rf"]),
        mae_gnn_fixed=float(gnn.loc[ds, "mae_fixed"]),
        mae_gnn_tuned=float(gnn.loc[ds, "mae_tuned"])))
out = pd.DataFrame(rows).sort_values("target").reset_index(drop=True)
out.to_csv(os.path.join(RESULTS_DIR, "per_target_correlations.csv"), index=False)
print("wrote per_target_correlations.csv,", len(out), "targets")

def f(x, d=2):
    return "--" if pd.isna(x) else f"{x:.{d}f}"
tgt = lambda s: s.replace("_", r"\_")

corr_rows = "\n".join(
    f"{tgt(r.target)} & {r.n} & {f(r.cliff_frac*100,1)} & {f(r.rho_dirichlet)} & "
    f"{f(r.rho_lipschitz)} & {f(r.rho_nbr_disp)} & {f(r.rho_sali_mean)} & {f(r.partial_nbr_disp_AD)} \\\\"
    for r in out.itertuples())
gnn_rows = "\n".join(
    f"{tgt(r.target)} & {r.n} & {f(r.mae_rf)} & {f(r.mae_gnn_fixed)} & {f(r.mae_gnn_tuned)} & {f(r.rogi,3)} \\\\"
    for r in out.itertuples())

with open(os.path.join(PAPER_DIR, "si_tables.tex"), "w") as fh:
    fh.write("% auto-generated by src/make_si_tables.py -- do not edit by hand\n")
    fh.write("\\newcommand{\\siCorrRows}{%\n" + corr_rows + "\n}\n\n")
    fh.write("\\newcommand{\\siGnnRows}{%\n" + gnn_rows + "\n}\n")
print("wrote paper/si_tables.tex")
